
services:
  apicalypso:
    container_name: apicalypso
    image: acrdevseavalue.azurecr.io/apicalypso:latest
    build:
      context: ./src/apicalypso
      dockerfile: dockerfile
    env_file:
      - ./src/apicalypso/.env
    environment:
      - APP_ENV=develop
    ports:
      - 5014:5014
    volumes:
      - ./src/apicalypso:/app
