# CI/CD file templates for GitHub Actions (DEV)

WORKFLOW_YML = "name: DEV API {app_name} Construye y despliega\n\non:\n#   push:\n#     branches:\n#       - main\n#     paths:\n#         - '{folder_name}/**'\n\n  workflow_dispatch:\n\njobs:\n  build-and-push:\n    runs-on: 'ubuntu-latest'\n    environment: 'development'\n\n    steps:\n    - uses: actions/checkout@v4\n\n    - name: Set up Docker Buildx\n      uses: docker/setup-buildx-action@v3\n\n    - name: Log in to registry\n      uses: docker/login-action@v3\n      with:\n        registry: ${{{{ secrets.ACR_SERVER }}}}\n        username: ${{{{ secrets.ACR_USERNAME }}}}\n        password: ${{{{ secrets.ACR_PASSWORD }}}}\n\n    - name: Build and push container image to registry\n      uses: docker/build-push-action@v5\n      with:\n        context: ./{folder_name}\n        push: true\n        tags: ${{{{ secrets.ACR_SERVER }}}}/{slug}:${{{{ github.sha }}}}\n        file: ./{folder_name}/Dockerfile\n\n  deploy:\n    runs-on: ubuntu-latest\n    needs: build-and-push\n    environment:\n      name: 'development'\n      url: ${{{{ steps.deploy-to-webapp.outputs.webapp-url }}}}\n\n    steps:\n    - name: Deploy to Azure Web App\n      id: deploy-to-webapp\n      uses: azure/webapps-deploy@v3\n      with:\n        app-name: ${{{{ vars.APP_NAME_001}}}}\n        slot-name: 'production'\n        publish-profile: ${{{{ secrets.PUBLISHPROFILE_DEV_001 }}}}\n        images: '${{{{ secrets.ACR_SERVER }}}}/{slug}:${{{{ github.sha }}}}'\n"

SET_SECRETS_PS1 = '# ---------------------------------------------\n# Entorno DEV\n# ---------------------------------------------\n$env = "development"\n# Secretos\n$fileSecrets = ".\\repo-secrets-dev.env"\ngh secret set --env $env -f $fileSecrets\n\n# Variables\n$fileVariables = ".\\repo-variables-dev.env"\ngh variable set --env $env -f $fileVariables\n\n# Credentials yml publish profile app-dev-api\n$filePublishProfile = ".\\repo-publishprofile-dev-001.yml"\n$secretName = "PUBLISHPROFILE_DEV_001"\n$publishProfileContent = Get-Content $filePublishProfile -Raw\n$publishProfileContent | gh secret set $secretName --env $env\n'

PUBLISH_PROFILE_PLACEHOLDER = '<>'

REPO_SECRETS_TEMPLATE = '# -------------------------------------------------\n# Secretos DEV ACR\n# -------------------------------------------------\nACR_SERVER="{acr_server}"\nACR_USERNAME="{acr_username}"\nACR_PASSWORD=""\n\n# ------------------------------------------------------------\n# Secretos DEV APP-API {project_name}\n# ------------------------------------------------------------\n# Base de datos postgresql\nusernameDB="{db_prod_username}"\npasswordDB="{db_prod_password}"\nservernameDB="{db_prod_server}"\ndatabasenameDB="{db_prod_dbname}"\n\n# API\nAPI_KEY="{api_key}"\nX_API_KEY="{x_api_key}"\nDOCS_API_KEY="{docs_api_key}"\nSECRET_KEY="{secret_key}"\nFERNET_KEY="{fernet_key}"\nALGORITHM="{algorithm}"\nAPP_ENV="{app_env}"\n\n# Usuarios de la api\nusernameAdmin="{admin_username}"\npasshashAdminAPI="{admin_password}"\n# PerroBot\npasshashAdmin="{passhash_admin_bot}"\nPERROBOT_TOKEN="{perrobot_token}"\n'

REPO_VARIABLES_TEMPLATE = '# ------------------------------------------\n# DEV Variables API\n# ------------------------------------------\nAPP_NAME_001="{app_name}"\n'
